### ISSUE TITLE
More information needed about the confirmation emails

### ISSUE THREAD

**Issue by SMH110** [SMH110/Pizza-website#111]
- I need the STORE PHONE
- I need the STORE URL
- Is it ok to send the same email subject to the store and user?
- in the store confirmation template at the bottom there is Delivery Address, when the Delivery method is Collection, do I have to display this section when just the user name will be appearing?

**Comment by massimocode** [comment]
- Store Phone and URL can be hardcoded directly in the template for now.
- The email subject for the customer should say "Your order was received".
- The delivery address should be on both emails (so that the customer also has a record of where they asked for the order to be delivered to) for delivery orders. For collection orders it should say Collect From and then the store's address (also hardcoded) in the same format as the Delivery address is displayed

**Comment by massimocode** [comment]
Store phone and Store URL can be obtained from the existing legacy website
