### ISSUE TITLE
Store email - Order received

### ISSUE THREAD

**Issue by SMH110** [SMH110/Pizza-website#35]
I want to receive order notifications by email to (...) with the subject “New order - £13.99 - John Smith” (New order – price – full name)

**Comment by massimocode** [comment]
<img width="488" alt="shop-email" src="https://cloud.githubusercontent.com/assets/3898363/22204659/082d4794-e16b-11e6-9a50-897bbd702d5b.PNG">

**Comment by SMH110** [comment]
For Store email, I am going to use Nodemailer PRO library, I am going to create new gmail account for the website and I am going to use this gmail account to send the emails to the store email.
I have tried Nodemailer PRO it is very fast, I received the email within 3 seconds.
the only issue I found that gmail automatically will stop node.js from singing to new account which I create 
so I have to turn on the Access for less secure apps.

**Comment by SMH110** [comment]
Or if you want I can use sendgrid server with sendgrid-nodejs

**Comment by massimocode** [comment]
# NPM Package for sending email
Nodemailer PRO is a paid for version, so we can't use that. I don't think we should use sendgrid-nodejs because it means using SendGrid, which is an email sending service and isn't free either. Nodemailer (not Nodemailer PRO) should hopefully be fine to use though (https://github.com/nodemailer/nodemailer).

# SMTP account for sending email
We'll need SMTP details for sending email. I propose we use the store's email account for now and see how that goes. But we'll need a test account too, preferably with the same provider (Outlook.com) for our testing and QA environments. I've just set that up:
`pizza-delivery-website-test`
`^yO*#A30$4(x01H`

- When will you send the email?
- What happens when the email failed to be sent? (Maybe because of an SMTP problem or email account blocked or something)
- Roughly what code changes will need to be made?
